sudo: false
addons:
  apt:
    packages:
    - pandoc

language: python

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

    - python: "2.7"
      env: TOXENV=docs

install: "pip install tox"
script: tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email:
    on_success: never
    on_failure: always


